#!/usr/bin/env python3
"""One-time migration: prepend a frozen serial (001..) to every finding ID.

NEW id = "<NNN>-<OLD>"  (zero-padded; old code kept as the descriptive suffix).

Order (so 001 == the current top of the work queue):
  tier 1  actionable  (Status==OPEN AND opus-ultra==LEGIT)  -> severity, then corroboration
  tier 2  everything else                                   -> same key
Once assigned the serial is IDENTITY and never changes (freeze model); the live
priority keeps living in BACKLOG.md's `#` column. New findings get the next free number.

Touches (all version-controlled, fully reversible):
  findings/<OLD>.md            -> findings/<NEW>.md   (+ the `# [OLD]` H1 inside)
  bugs.csv          id column
  assessments.csv   first field
  BUG-HUNT-ALL-IN-ONE.md       `### [OLD]` headers   (so re-scaffold still finds claims)
  BACKLOG.md / REVIEW.md       regenerated by bughunt.py afterwards
  reindex-map.csv              old_id,new_id  (written for reference)

Usage:
  python reindex.py            # DRY RUN: validate + print preview + write reindex-map.csv
  python reindex.py --apply    # perform the migration, then regenerate BACKLOG/REVIEW
"""
import csv
import re
import sys

import bughunt as bh  # reuse the tool's proven readers + ranking


def build_order():
    bugs = bh.read_bugs()
    per, agents = bh.read_assessments()
    actionable, rest = [], []
    for bid, meta in bugs.items():
        p = bh.FIND / f"{bid}.md"
        status = bh.ticket_status(p) if p.exists() else "OPEN"
        gate = per.get(bid, {}).get(bh.GATE, ("", "", ""))[0]
        legit = sum(per.get(bid, {}).get(a, ("",))[0] == "LEGIT" for a in agents)
        key = (-bh.sevw(meta["severity"]), -legit, bid)
        (actionable if (status == "OPEN" and gate == "LEGIT") else rest).append((key, bid))
    actionable.sort()
    rest.sort()
    ordered = [bid for _, bid in actionable] + [bid for _, bid in rest]
    return bugs, ordered, len(actionable)


def main():
    apply = "--apply" in sys.argv[1:]
    bugs, ordered, n_actionable = build_order()

    # validate id<->file bijection before touching anything
    ids = set(bugs)
    files = {p.stem for p in bh.FIND.glob("*.md")}
    missing_files = sorted(ids - files)
    orphan_files = sorted(files - ids)
    if missing_files or orphan_files:
        print("REFUSING — bugs.csv and findings/ are out of sync:")
        if missing_files:
            print(f"  {len(missing_files)} ids with no ticket file, e.g. {missing_files[:5]}")
        if orphan_files:
            print(f"  {len(orphan_files)} ticket files not in bugs.csv, e.g. {orphan_files[:5]}")
        sys.exit(1)

    width = max(3, len(str(len(ordered))))
    mapping = {old: f"{i:0{width}d}-{old}" for i, old in enumerate(ordered, 1)}

    # always (re)write the map so it can be eyeballed / used to resolve prose refs
    map_path = bh.HERE / "reindex-map.csv"
    with map_path.open("w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["serial", "old_id", "new_id"])
        for i, old in enumerate(ordered, 1):
            w.writerow([f"{i:0{width}d}", old, mapping[old]])

    print(f"{len(ordered)} findings · {n_actionable} actionable (001..{n_actionable:0{width}d}) · "
          f"rest {n_actionable+1:0{width}d}..{len(ordered):0{width}d} · width {width}")
    print(f"map written: {map_path.name}\n")
    print("first 12 (top of the work queue):")
    for i, old in enumerate(ordered[:12], 1):
        print(f"  {old:<14} -> {mapping[old]}")
    print(f"tier-2 boundary  ...{ordered[n_actionable-1]} | {ordered[n_actionable]}...")

    if not apply:
        print("\nDRY RUN — nothing changed. Re-run with --apply to perform the migration.")
        return

    # 1) bugs.csv — remap id, preserve every other column
    with bh.BUGS.open(encoding="utf-8") as fh:
        r = csv.DictReader(fh)
        fields, rows = r.fieldnames, list(r)
    for row in rows:
        row["id"] = mapping[row["id"].strip()]
    with bh.BUGS.open("w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)

    # 2) assessments.csv — remap first field only, byte-preserve the rest
    lines = bh.ASSESS.read_text(encoding="utf-8").splitlines()
    out = []
    for ln in lines:
        if not ln.strip() or ln.startswith("id,agent,"):
            out.append(ln)
            continue
        p = ln.split(",", 4)
        p[0] = mapping.get(p[0].strip(), p[0])
        out.append(",".join(p))
    bh.ASSESS.write_text("\n".join(out) + "\n", encoding="utf-8")

    # 3) rename tickets + fix the `# [OLD]` H1 (new names have a digit prefix -> no collisions)
    for old, new in mapping.items():
        src, dst = bh.FIND / f"{old}.md", bh.FIND / f"{new}.md"
        txt = src.read_text(encoding="utf-8")
        txt = re.sub(r"^# \[" + re.escape(old) + r"\]", f"# [{new}]", txt, count=1, flags=re.M)
        dst.write_text(txt, encoding="utf-8")
        if dst != src:
            src.unlink()

    # 4) BUG-HUNT-ALL-IN-ONE.md — remap `### [OLD]` headers in one pass
    if bh.REPORT.exists():
        rpt = bh.REPORT.read_text(encoding="utf-8", errors="replace")
        def hdr(m):
            return m.group(1) + mapping.get(m.group(2), m.group(2)) + m.group(3)
        rpt = re.sub(r"(^###\s+\[)([A-Z0-9][A-Z0-9-]*)(\])", hdr, rpt, flags=re.M)
        bh.REPORT.write_text(rpt, encoding="utf-8")

    # 5) regenerate the derived views
    bh.backlog()
    bh.build_review()
    print("\nAPPLIED. BACKLOG.md / REVIEW.md regenerated. Review `git status` then commit.")


if __name__ == "__main__":
    main()
